import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar/Navbar";
import LeftNav from "@/components/shared/LeftNav/LeftNav";
import RightNav from "@/components/shared/RightNav/RightNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dua Page",
  description: "Generated by Dua Page",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-[1600px] mx-auto ">
          <Navbar />
          <div className="grid grid-cols-[100px,1fr,330px] gap-6">
            <LeftNav />
            <div className="w-full ">{children}</div>
            <RightNav />
          </div>
        </div>
      </body>
    </html>
  );
}
